name: flutter_downloader
description: Powerful plugin making it easy to download files.
version: 1.9.0
repository: https://github.com/fluttercommunity/flutter_downloader
issue_tracker: https://github.com/fluttercommunity/flutter_downloader/issues
maintainer: Bartek Pacia (@bartekpacia)


environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: ^14.4.0


flutter:
  plugin:
    platforms:
      android:
        package: vn.hunghd.flutterdownloader
        pluginClass: FlutterDownloaderPlugin
      ios:
        pluginClass: FlutterDownloaderPlugin

